# starship.toml - Evelyn King

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

[shell]
zsh_indicator = ""  # MacOS default is zsh

fish_indicator = "ğŸŸ"
style = "cyan bold"
disabled = false

[python]
detect_extensions = []

[conda]
ignore_base = false
