# starship.toml - Evelyn King

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

[shell]
bash_indicator = ""

fish_indicator = "ğŸŸ"
style = "cyan bold"
disabled = false

[python]
detect_extensions = []

[conda]
ignore_base = false
