# starship.toml - Evelyn King

add_newline = false
command_timeout = 1000

[shell]
bash_indicator = ""

fish_indicator = "ğŸŸ"
style = "cyan bold"
disabled = false

[python]
detect_extensions = []

[conda]
ignore_base = false

